apiVersion: v1
entries:
  airflow:
  - apiVersion: v1
    appVersion: 1.10.12
    created: "2021-02-05T10:28:03.907433+01:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.helm.sh/stable
      version: 8.6.4
    - condition: redis.enabled
      name: redis
      repository: https://charts.helm.sh/stable
      version: 10.5.7
    description: airflow is a platform to programmatically author, schedule, and monitor
      workflows
    digest: 7a63c1ddbb0688bd09ae334adca2d0da48e83db8cff05daa4be5ccc7b146b101
    home: https://airflow.apache.org/
    icon: https://airflow.apache.org/_images/pin_large.png
    keywords:
    - airflow
    - dag
    - workflow
    maintainers:
    - name: gsemet
      url: https://github.com/gsemet
    - name: thesuperzapper
      url: https://github.com/thesuperzapper
    name: airflow
    sources:
    - https://github.com/tiqets/charts/tree/main/charts/airflow
    urls:
    - https://tiqets.github.io/charts/airflow-7.16.0.tgz
    version: 7.16.0
generated: "2021-02-05T10:28:03.895518+01:00"
